                                                                                                                                                                    import streamlit as st
                                                                                                                                                                    import sqlite3
                                                                                                                                                                    import pandas as pd

                                                                                                                                                                    # 1. Database Connection
                                                                                                                                                                    conn = sqlite3.connect("league.db", check_same_thread=False)
                                                                                                                                                                    c = conn.cursor()
                                                                                                                                                                    c.execute('''CREATE TABLE IF NOT EXISTS teams 
                                                                                                                                                                                 (name TEXT PRIMARY KEY, mp INTEGER DEFAULT 0, gf INTEGER DEFAULT 0, 
                                                                                                                                                                                               ga INTEGER DEFAULT 0, gd INTEGER DEFAULT 0, pts INTEGER DEFAULT 0)''')
                                                                                                                                                                                               conn.commit()

                                                                                                                                                                                               # 2. App Styling
                                                                                                                                                                                               st.title("🏆 GOAL-QUERY League")

                                                                                                                                                                                               # 3. Sidebar Navigation
                                                                                                                                                                                               page = st.sidebar.selectbox("Go to:", ["Standings", "Add Teams", "Update Scores"])

                                                                                                                                                                                               if page == "Add Teams":
                                                                                                                                                                                                   st.subheader("Register a New Team")
                                                                                                                                                                                                       new_team = st.text_input("Enter name")
                                                                                                                                                                                                           if st.button("Add to League"):
                                                                                                                                                                                                                   if new_team:
                                                                                                                                                                                                                               try:
                                                                                                                                                                                                                                               c.execute("INSERT INTO teams (name) VALUES (?)", (new_team,))
                                                                                                                                                                                                                                                               conn.commit()
                                                                                                                                                                                                                                                                               st.success(f"{new_team} added!")
                                                                                                                                                                                                                                                                                           except:
                                                                                                                                                                                                                                                                                                           st.error("This team is already registered!")

                                                                                                                                                                                                                                                                                                           elif page == "Standings":
                                                                                                                                                                                                                                                                                                               st.subheader("League Table")
                                                                                                                                                                                                                                                                                                                   df = pd.read_sql_query("SELECT * FROM teams ORDER BY pts DESC, gd DESC", conn)
                                                                                                                                                                                                                                                                                                                       if df.empty:
                                                                                                                                                                                                                                                                                                                               st.info("No teams yet. Go to 'Add Teams' to start.")
                                                                                                                                                                                                                                                                                                                                   else:
                                                                                                                                                                                                                                                                                                                                           st.table(df)

                                                                                                                                                                                                                                                                                                                                           elif page == "Update Scores":
                                                                                                                                                                                                                                                                                                                                               st.subheader("Record Match Result")
                                                                                                                                                                                                                                                                                                                                                   teams = [r[0] for r in c.execute("SELECT name FROM teams").fetchall()]
                                                                                                                                                                                                                                                                                                                                                       if len(teams) < 2:
                                                                                                                                                                                                                                                                                                                                                               st.warning("You need at least 2 teams to record a score.")
                                                                                                                                                                                                                                                                                                                                                                   else:
                                                                                                                                                                                                                                                                                                                                                                           with st.form("score_input"):
                                                                                                                                                                                                                                                                                                                                                                                       t1 = st.selectbox("Home Team", teams)
                                                                                                                                                                                                                                                                                                                                                                                                   s1 = st.number_input("Home Goals", 0)
                                                                                                                                                                                                                                                                                                                                                                                                               t2 = st.selectbox("Away Team", teams, index=1)
                                                                                                                                                                                                                                                                                                                                                                                                                           s2 = st.number_input("Away Goals", 0)

                                                                                                                                                                                                                                                                                                                                                                                                                                                   if st.form_submit_button("Submit Result"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   p1, p2 = (3, 0) if s1 > s2 else ((1, 1) if s1 == s2 else (0, 3))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   c.execute("UPDATE teams SET mp=mp+1, gf=gf+?, ga=ga+?, gd=gd+?, pts=pts+? WHERE name=?", (s1, s2, s1-s2, p1, t1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   c.execute("UPDATE teams SET mp=mp+1, gf=gf+?, ga=ga+?, gd=gd+?, pts=pts+? WHERE name=?", (s2, s1, s2-s1, p2, t2))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   st.success("Standings Updated!")                                               